import org.codehaus.grails.portlets.container.liferay.LiferayPortletContainerAdapter

class PortletsLiferayGrailsPlugin {
    def version = "0.4"
    def grailsVersion = "2.0 > *"
    def loadAfter = ['portlets']
    def author = "Kenji Nakamura"
    def authorEmail = "kenji_nakamura@diva-america.com"
    def title = "Liferay Portal Portlets Plugin"
    def description = 'Generates the configuration files for Liferay Portal in addition to portlet.xml generated by portlets plugin.'
    def documentation = "http://grails.org/plugin/portlets-liferay"

    String license = 'MIT'
//    def issueManagement = [system: 'JIRA', url: 'http://jira.grails.org/browse/???']
    def scm = [url: 'https://github.com/grails-portlets-plugin/grails-portlets-liferay']

    def doWithSpring = {
        portletContainerAdapter(LiferayPortletContainerAdapter)
    }
}
